name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'yes' to confirm destruction of infrastructure"
        required: true
        default: "no"

jobs:
  destroy_infra:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'yes'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
      
      - name: Configure AWS CLI
        run: |
         aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
         aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
         aws configure set region "${{ secrets.AWS_REGION }}"

      - name: Set working directory
        run: cd appu

      - name: Destroy Infrastructure
        run: |
          terraform init
          terraform destroy -auto-approve
        
          
